# Generated by Django 5.2.10 on 2026-01-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0003_onetimecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authcore.clientapp'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='authuser',
            unique_together={('email', 'client')},
        ),
    ]
