# Generated by Django 5.2.10 on 2026-01-16 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0004_authuser_client_alter_authuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authcore.clientapp'),
        ),
    ]
